# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from arena.v1 import arena_pb2 as arena_dot_v1_dot_arena__pb2
from arena.v1 import trajectory_pb2 as arena_dot_v1_dot_trajectory__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arena/v1/arena_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArenaServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRollout = channel.unary_unary(
                '/arena.v1.ArenaService/CreateRollout',
                request_serializer=arena_dot_v1_dot_arena__pb2.CreateRolloutRequest.SerializeToString,
                response_deserializer=arena_dot_v1_dot_arena__pb2.CreateRolloutResponse.FromString,
                _registered_method=True)
        self.GetRollout = channel.unary_unary(
                '/arena.v1.ArenaService/GetRollout',
                request_serializer=arena_dot_v1_dot_arena__pb2.GetRolloutRequest.SerializeToString,
                response_deserializer=arena_dot_v1_dot_arena__pb2.Rollout.FromString,
                _registered_method=True)
        self.StopRollout = channel.unary_unary(
                '/arena.v1.ArenaService/StopRollout',
                request_serializer=arena_dot_v1_dot_arena__pb2.StopRolloutRequest.SerializeToString,
                response_deserializer=arena_dot_v1_dot_arena__pb2.StopRolloutResponse.FromString,
                _registered_method=True)
        self.ListRollouts = channel.unary_unary(
                '/arena.v1.ArenaService/ListRollouts',
                request_serializer=arena_dot_v1_dot_arena__pb2.ListRolloutsRequest.SerializeToString,
                response_deserializer=arena_dot_v1_dot_arena__pb2.ListRolloutsResponse.FromString,
                _registered_method=True)
        self.StreamTrajectory = channel.unary_stream(
                '/arena.v1.ArenaService/StreamTrajectory',
                request_serializer=arena_dot_v1_dot_arena__pb2.StreamTrajectoryRequest.SerializeToString,
                response_deserializer=arena_dot_v1_dot_trajectory__pb2.TrajectoryStep.FromString,
                _registered_method=True)
        self.GetTrajectory = channel.unary_unary(
                '/arena.v1.ArenaService/GetTrajectory',
                request_serializer=arena_dot_v1_dot_arena__pb2.GetTrajectoryRequest.SerializeToString,
                response_deserializer=arena_dot_v1_dot_arena__pb2.Trajectory.FromString,
                _registered_method=True)


class ArenaServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateRollout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRollout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRollout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRollouts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTrajectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrajectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArenaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRollout': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRollout,
                    request_deserializer=arena_dot_v1_dot_arena__pb2.CreateRolloutRequest.FromString,
                    response_serializer=arena_dot_v1_dot_arena__pb2.CreateRolloutResponse.SerializeToString,
            ),
            'GetRollout': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRollout,
                    request_deserializer=arena_dot_v1_dot_arena__pb2.GetRolloutRequest.FromString,
                    response_serializer=arena_dot_v1_dot_arena__pb2.Rollout.SerializeToString,
            ),
            'StopRollout': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRollout,
                    request_deserializer=arena_dot_v1_dot_arena__pb2.StopRolloutRequest.FromString,
                    response_serializer=arena_dot_v1_dot_arena__pb2.StopRolloutResponse.SerializeToString,
            ),
            'ListRollouts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRollouts,
                    request_deserializer=arena_dot_v1_dot_arena__pb2.ListRolloutsRequest.FromString,
                    response_serializer=arena_dot_v1_dot_arena__pb2.ListRolloutsResponse.SerializeToString,
            ),
            'StreamTrajectory': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTrajectory,
                    request_deserializer=arena_dot_v1_dot_arena__pb2.StreamTrajectoryRequest.FromString,
                    response_serializer=arena_dot_v1_dot_trajectory__pb2.TrajectoryStep.SerializeToString,
            ),
            'GetTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrajectory,
                    request_deserializer=arena_dot_v1_dot_arena__pb2.GetTrajectoryRequest.FromString,
                    response_serializer=arena_dot_v1_dot_arena__pb2.Trajectory.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arena.v1.ArenaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arena.v1.ArenaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArenaService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRollout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.ArenaService/CreateRollout',
            arena_dot_v1_dot_arena__pb2.CreateRolloutRequest.SerializeToString,
            arena_dot_v1_dot_arena__pb2.CreateRolloutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRollout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.ArenaService/GetRollout',
            arena_dot_v1_dot_arena__pb2.GetRolloutRequest.SerializeToString,
            arena_dot_v1_dot_arena__pb2.Rollout.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRollout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.ArenaService/StopRollout',
            arena_dot_v1_dot_arena__pb2.StopRolloutRequest.SerializeToString,
            arena_dot_v1_dot_arena__pb2.StopRolloutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRollouts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.ArenaService/ListRollouts',
            arena_dot_v1_dot_arena__pb2.ListRolloutsRequest.SerializeToString,
            arena_dot_v1_dot_arena__pb2.ListRolloutsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arena.v1.ArenaService/StreamTrajectory',
            arena_dot_v1_dot_arena__pb2.StreamTrajectoryRequest.SerializeToString,
            arena_dot_v1_dot_trajectory__pb2.TrajectoryStep.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.ArenaService/GetTrajectory',
            arena_dot_v1_dot_arena__pb2.GetTrajectoryRequest.SerializeToString,
            arena_dot_v1_dot_arena__pb2.Trajectory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
