# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openagora/v1/sandbox.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'openagora/v1/sandbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aopenagora/v1/sandbox.proto\x12\x0copenagora.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n\x14SandboxCreateRequest\x12\r\n\x05image\x18\x01 \x01(\t\x12\x0e\n\x06memory\x18\x02 \x01(\t\x12\x0c\n\x04\x63pus\x18\x03 \x01(\x01\x12\x41\n\x08\x65nv_vars\x18\x04 \x03(\x0b\x32/.openagora.v1.SandboxCreateRequest.EnvVarsEntry\x12\x11\n\ttask_file\x18\x05 \x01(\x0c\x12\x17\n\x0ftimeout_seconds\x18\x06 \x01(\x05\x1a.\n\x0c\x45nvVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\x15SandboxCreateResponse\x12\x12\n\nsandbox_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"^\n\x10SandboxLifecycle\x12\x12\n\nsandbox_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12&\n\x02ts\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"?\n\nExecResult\x12\x11\n\texit_code\x18\x01 \x01(\x05\x12\x0e\n\x06stdout\x18\x02 \x01(\x0c\x12\x0e\n\x06stderr\x18\x03 \x01(\x0c\x42\x36Z4github.com/albert-lv/OpenAgora/go/proto/openagora/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openagora.v1.sandbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/albert-lv/OpenAgora/go/proto/openagora/v1'
  _globals['_SANDBOXCREATEREQUEST_ENVVARSENTRY']._loaded_options = None
  _globals['_SANDBOXCREATEREQUEST_ENVVARSENTRY']._serialized_options = b'8\001'
  _globals['_SANDBOXCREATEREQUEST']._serialized_start=78
  _globals['_SANDBOXCREATEREQUEST']._serialized_end=304
  _globals['_SANDBOXCREATEREQUEST_ENVVARSENTRY']._serialized_start=258
  _globals['_SANDBOXCREATEREQUEST_ENVVARSENTRY']._serialized_end=304
  _globals['_SANDBOXCREATERESPONSE']._serialized_start=306
  _globals['_SANDBOXCREATERESPONSE']._serialized_end=365
  _globals['_SANDBOXLIFECYCLE']._serialized_start=367
  _globals['_SANDBOXLIFECYCLE']._serialized_end=461
  _globals['_EXECRESULT']._serialized_start=463
  _globals['_EXECRESULT']._serialized_end=526
# @@protoc_insertion_point(module_scope)
