// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: arena/v1/arena.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArenaService_CreateRollout_FullMethodName    = "/arena.v1.ArenaService/CreateRollout"
	ArenaService_GetRollout_FullMethodName       = "/arena.v1.ArenaService/GetRollout"
	ArenaService_StopRollout_FullMethodName      = "/arena.v1.ArenaService/StopRollout"
	ArenaService_ListRollouts_FullMethodName     = "/arena.v1.ArenaService/ListRollouts"
	ArenaService_StreamTrajectory_FullMethodName = "/arena.v1.ArenaService/StreamTrajectory"
	ArenaService_GetTrajectory_FullMethodName    = "/arena.v1.ArenaService/GetTrajectory"
)

// ArenaServiceClient is the client API for ArenaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArenaServiceClient interface {
	CreateRollout(ctx context.Context, in *CreateRolloutRequest, opts ...grpc.CallOption) (*CreateRolloutResponse, error)
	GetRollout(ctx context.Context, in *GetRolloutRequest, opts ...grpc.CallOption) (*Rollout, error)
	StopRollout(ctx context.Context, in *StopRolloutRequest, opts ...grpc.CallOption) (*StopRolloutResponse, error)
	ListRollouts(ctx context.Context, in *ListRolloutsRequest, opts ...grpc.CallOption) (*ListRolloutsResponse, error)
	StreamTrajectory(ctx context.Context, in *StreamTrajectoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrajectoryStep], error)
	GetTrajectory(ctx context.Context, in *GetTrajectoryRequest, opts ...grpc.CallOption) (*Trajectory, error)
}

type arenaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArenaServiceClient(cc grpc.ClientConnInterface) ArenaServiceClient {
	return &arenaServiceClient{cc}
}

func (c *arenaServiceClient) CreateRollout(ctx context.Context, in *CreateRolloutRequest, opts ...grpc.CallOption) (*CreateRolloutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRolloutResponse)
	err := c.cc.Invoke(ctx, ArenaService_CreateRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) GetRollout(ctx context.Context, in *GetRolloutRequest, opts ...grpc.CallOption) (*Rollout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rollout)
	err := c.cc.Invoke(ctx, ArenaService_GetRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) StopRollout(ctx context.Context, in *StopRolloutRequest, opts ...grpc.CallOption) (*StopRolloutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRolloutResponse)
	err := c.cc.Invoke(ctx, ArenaService_StopRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) ListRollouts(ctx context.Context, in *ListRolloutsRequest, opts ...grpc.CallOption) (*ListRolloutsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRolloutsResponse)
	err := c.cc.Invoke(ctx, ArenaService_ListRollouts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaServiceClient) StreamTrajectory(ctx context.Context, in *StreamTrajectoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrajectoryStep], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArenaService_ServiceDesc.Streams[0], ArenaService_StreamTrajectory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTrajectoryRequest, TrajectoryStep]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArenaService_StreamTrajectoryClient = grpc.ServerStreamingClient[TrajectoryStep]

func (c *arenaServiceClient) GetTrajectory(ctx context.Context, in *GetTrajectoryRequest, opts ...grpc.CallOption) (*Trajectory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Trajectory)
	err := c.cc.Invoke(ctx, ArenaService_GetTrajectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArenaServiceServer is the server API for ArenaService service.
// All implementations must embed UnimplementedArenaServiceServer
// for forward compatibility.
type ArenaServiceServer interface {
	CreateRollout(context.Context, *CreateRolloutRequest) (*CreateRolloutResponse, error)
	GetRollout(context.Context, *GetRolloutRequest) (*Rollout, error)
	StopRollout(context.Context, *StopRolloutRequest) (*StopRolloutResponse, error)
	ListRollouts(context.Context, *ListRolloutsRequest) (*ListRolloutsResponse, error)
	StreamTrajectory(*StreamTrajectoryRequest, grpc.ServerStreamingServer[TrajectoryStep]) error
	GetTrajectory(context.Context, *GetTrajectoryRequest) (*Trajectory, error)
	mustEmbedUnimplementedArenaServiceServer()
}

// UnimplementedArenaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArenaServiceServer struct{}

func (UnimplementedArenaServiceServer) CreateRollout(context.Context, *CreateRolloutRequest) (*CreateRolloutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRollout not implemented")
}
func (UnimplementedArenaServiceServer) GetRollout(context.Context, *GetRolloutRequest) (*Rollout, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRollout not implemented")
}
func (UnimplementedArenaServiceServer) StopRollout(context.Context, *StopRolloutRequest) (*StopRolloutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRollout not implemented")
}
func (UnimplementedArenaServiceServer) ListRollouts(context.Context, *ListRolloutsRequest) (*ListRolloutsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRollouts not implemented")
}
func (UnimplementedArenaServiceServer) StreamTrajectory(*StreamTrajectoryRequest, grpc.ServerStreamingServer[TrajectoryStep]) error {
	return status.Error(codes.Unimplemented, "method StreamTrajectory not implemented")
}
func (UnimplementedArenaServiceServer) GetTrajectory(context.Context, *GetTrajectoryRequest) (*Trajectory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrajectory not implemented")
}
func (UnimplementedArenaServiceServer) mustEmbedUnimplementedArenaServiceServer() {}
func (UnimplementedArenaServiceServer) testEmbeddedByValue()                      {}

// UnsafeArenaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArenaServiceServer will
// result in compilation errors.
type UnsafeArenaServiceServer interface {
	mustEmbedUnimplementedArenaServiceServer()
}

func RegisterArenaServiceServer(s grpc.ServiceRegistrar, srv ArenaServiceServer) {
	// If the following call panics, it indicates UnimplementedArenaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArenaService_ServiceDesc, srv)
}

func _ArenaService_CreateRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).CreateRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_CreateRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).CreateRollout(ctx, req.(*CreateRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_GetRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).GetRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_GetRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).GetRollout(ctx, req.(*GetRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_StopRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).StopRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_StopRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).StopRollout(ctx, req.(*StopRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_ListRollouts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolloutsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).ListRollouts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_ListRollouts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).ListRollouts(ctx, req.(*ListRolloutsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArenaService_StreamTrajectory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTrajectoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ArenaServiceServer).StreamTrajectory(m, &grpc.GenericServerStream[StreamTrajectoryRequest, TrajectoryStep]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArenaService_StreamTrajectoryServer = grpc.ServerStreamingServer[TrajectoryStep]

func _ArenaService_GetTrajectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrajectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServiceServer).GetTrajectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArenaService_GetTrajectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServiceServer).GetTrajectory(ctx, req.(*GetTrajectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArenaService_ServiceDesc is the grpc.ServiceDesc for ArenaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArenaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arena.v1.ArenaService",
	HandlerType: (*ArenaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRollout",
			Handler:    _ArenaService_CreateRollout_Handler,
		},
		{
			MethodName: "GetRollout",
			Handler:    _ArenaService_GetRollout_Handler,
		},
		{
			MethodName: "StopRollout",
			Handler:    _ArenaService_StopRollout_Handler,
		},
		{
			MethodName: "ListRollouts",
			Handler:    _ArenaService_ListRollouts_Handler,
		},
		{
			MethodName: "GetTrajectory",
			Handler:    _ArenaService_GetTrajectory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTrajectory",
			Handler:       _ArenaService_StreamTrajectory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arena/v1/arena.proto",
}
